# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 693429498512.dkr.ecr.ap-southeast-2.amazonaws.com/platform-enablement/gusbot
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: ops-gus-bot
  type: ClusterIP
resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi
build: "0"
