#! /bin/bash

set -e

# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOCKER_REGISTRY=693429498512.dkr.ecr.ap-southeast-2.amazonaws.com
APP_NAME=platform-enablement/gusbot
IMAGE_TAG=${1:-dev}
IMAGE=${DOCKER_REGISTRY}/${APP_NAME}:${IMAGE_TAG}

# $DIR/build ${IMAGE}

echo "+++ Pushing docker image to ECR..."
`aws ecr get-login --region ap-southeast-2 --registry-ids 693429498512`
echo ${IMAGE}
docker push ${IMAGE}
