# 1. build gusbot service
version: '2'
services:
  gusbot:
    build: .
    # volumes:
    # - ./slackbot/plugins1/.:/app/slackbot/plugins/
    # -

# volume:
# 2. create a persistent volume

# 3. a service that run the Gusbot with the Volume created.
