---
steps:
  - name: "docker: publish docker image"
    command: deployment/bin/publish ${BUILDKITE_BUILD_NUMBER}.${BUILDKITE_COMMIT:0:5}
    branches: master
    agents:
      queue: cluster-preprod

  - wait


  - name: ":aws: Deploy to SIT"
    command: deployment/bin/deploy_aws sit ${BUILDKITE_BUILD_NUMBER}.${BUILDKITE_COMMIT:0:5}
    branches: master
    agents:
      queue: cluster-preprod

  - wait

  - name: ":k8s: Deploy to SIT Kubernetes"
    command: APPLICATION_VERSION=${BUILDKITE_BUILD_NUMBER}.${BUILDKITE_COMMIT:0:5} deployment/bin/deploy
    branches: master
    agents:
      queue: cluster-preprod
    env:
      ENVIRONMENT: sit
      APPLICATION_IMAGE: 693429498512.dkr.ecr.ap-southeast-2.amazonaws.com/platform-enablement/gusbot #without version
