---
steps:
  # unit tests
  - command: make test
    label: ':hammer:'
    agents:
      queue: central-dev

  # publish image
  - command: make publish
    label: ':docker:'
    agents:
      queue: central-dev

  - wait:

  # deploy to preprod
  - command: make deploy/dev
    label: ':shipit: [DEV]'
    agents:
      queue: central-dev

  - block: 'Deploy to prod?'
    branches: master

  # deploy to prod
  - command: make deploy/prod
    label: ':shipit: [PROD]'
    branches: master
    agents:
      queue: central-prod

