---
steps:
  # unit tests
  - label: ':hammer:'
    command: make test
    agents:
      queue: 'pe-dev-dflt'

  - label: 'build and publish Docker image for the demo app'
    command: './deployment/bin/build_publish.sh ${BUILDKITE_BUILD_NUMBER}'
    plugins:
      ecr#v1.1.4:
        login: true
    agents:
      queue: 'pe-dev-dflt'

  - label: ':kubernetes: Deploy to Europa-Preprod'
    # ${BUILDKITE_BUILD_NUMBER} should be a valid Docker image tag available in the
    # Docker image repository mentioned in the deployment file.
    command:  'deployment/bin/deploy_europa.sh europa-preprod ${BUILDKITE_BUILD_NUMBER}'
    branches: 'master'
    agents:
      # your team's queue
      queue: 'europa-preprod-platform-enablement'


  - block: ":godmode: deploy PROD??"

  - label: ':kubernetes: Deploy to Europa'
    # ${BUILDKITE_BUILD_NUMBER} should be a valid Docker image tag available in the
    # Docker image repository mentioned in the deployment file.
    command:  'deployment/bin/deploy_europa.sh europa ${BUILDKITE_BUILD_NUMBER}'
    branches: 'master'
    agents:
      # your team's queue
      queue: 'europa-platform-enablement'
