kubectl:
  image: lachlanevenson/k8s-kubectl:v1.6.4
  working_dir: /app
  volumes:
    - ".:/app/deployment"
    - "$HOME/.kube:/root/.kube"

ktmpl:
  image: inquicker/ktmpl:0.7.0
  working_dir: /app
  volumes:
    - ".:/app/deployment"

stackup:
  image: realestate/stackup:latest
  working_dir: /app
  volumes:
    - ".:/app/deployment"
    - "$HOME/.aws:/root/.aws"
